# Based off <https://elis.nu/blog/2022/10/outsourcing-nixos-compile-time-to-microsoft/>

name: Cachix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: handelsblattmediagroup/lix-quick-install-action@v3.0.4

      - name: Cachix setup
        uses: cachix/cachix-action@v12
        with:
          name: somasis
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Build ilo
        run: nix-build . -A nixosConfigurations.ilo.config.system.build.toplevel

      - name: Cache built derivation
        run: realpath result | cachix push somasis
